// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: RobotState.proto

#include "RobotState.pb.h"
#include "RobotState.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace robotonotos {

static const char* RobotState_method_names[] = {
  "/robotonotos.RobotState/GetImage",
};

std::unique_ptr< RobotState::Stub> RobotState::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RobotState::Stub> stub(new RobotState::Stub(channel));
  return stub;
}

RobotState::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetImage_(RobotState_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RobotState::Stub::GetImage(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::robotonotos::ImageReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetImage_, context, request, response);
}

void RobotState::Stub::experimental_async::GetImage(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::robotonotos::ImageReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetImage_, context, request, response, std::move(f));
}

void RobotState::Stub::experimental_async::GetImage(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::robotonotos::ImageReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetImage_, context, request, response, std::move(f));
}

void RobotState::Stub::experimental_async::GetImage(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::robotonotos::ImageReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetImage_, context, request, response, reactor);
}

void RobotState::Stub::experimental_async::GetImage(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::robotonotos::ImageReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetImage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::robotonotos::ImageReply>* RobotState::Stub::AsyncGetImageRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::robotonotos::ImageReply>::Create(channel_.get(), cq, rpcmethod_GetImage_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::robotonotos::ImageReply>* RobotState::Stub::PrepareAsyncGetImageRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::robotonotos::ImageReply>::Create(channel_.get(), cq, rpcmethod_GetImage_, context, request, false);
}

RobotState::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RobotState_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RobotState::Service, ::google::protobuf::Empty, ::robotonotos::ImageReply>(
          [](RobotState::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::robotonotos::ImageReply* resp) {
               return service->GetImage(ctx, req, resp);
             }, this)));
}

RobotState::Service::~Service() {
}

::grpc::Status RobotState::Service::GetImage(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::robotonotos::ImageReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace robotonotos

